#!/usr/bin/env bash
set -e

# download, if file is missing
if [[ -f "$1" ]]; then
    echo "> using cache: $1"
else
    echo "> download: $2"
    curl -L -o $1 --fail $2
fi

# sha256 check
if [[ "$1" =~ ^.*\.sha256sum ]]; then
    echo "> verifying downloaded files: $1"
    cd $(dirname "$1") && sha256sum -c --ignore-missing $1
fi

# gpg signature verification
if [[ "$1" =~ ^.*\.asc ]]; then
    echo "> verifying with signature $1"
    gpg --verify "$1" "${1::-4}"
fi
