#!/usr/bin/env bash
set -e

# config
installRoot=${INSTALLROOT:-/rootfs}
releasever=${RELEASEVER:-$(rpm -E %{rhel})}

# exec
microdnf --noplugins --config=/etc/dnf/dnf.conf --setopt=cachedir=/var/cache/microdnf --setopt=reposdir=/etc/yum.repos.d --setopt=varsdir=/etc/dnf --installroot=$installRoot --releasever $releasever remove "$@"
