# syntax=docker.io/docker/dockerfile:1.3
# image=quay.io/cidverse/sonarscannercli

# compile the twitch cli binary
# 
FROM quay.io/cidverse/common-build:latest

# renovate: datasource=github-releases depName=SonarSource/sonar-scanner-cli
ARG SONARSCANNERCLI_VERSION=4.7.0.2747

RUN mkdir -p /cache /app/sonarscanner \
&&  curl -L -o /cache/sonar-scanner-cli-${SONARSCANNERCLI_VERSION}-linux.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONARSCANNERCLI_VERSION}-linux.zip \
&&  unzip /cache/sonar-scanner-cli-${SONARSCANNERCLI_VERSION}-linux.zip -d /tmp \
&&  mv /tmp/sonar-scanner-${SONARSCANNERCLI_VERSION}-linux/* /app/sonarscanner

# runtime image
#
FROM quay.io/cidverse/common-minimal:latest
ENV PATH="${PATH}:/app/sonarscanner/bin" \
    JAVA_HOME=/usr/lib/jvm/jre-11-openjdk

RUN microdnf install -y zlib.i686 git python3 java-11-openjdk
COPY --from=0 /app/sonarscanner /app/sonarscanner

USER 1001
CMD ["sonar-scanner"]
