#!/usr/bin/env bash

# config
installRoot=${INSTALLROOT:-/rootfs}

# exec
microdnf --noplugins --config=/etc/dnf/dnf.conf --setopt=cachedir=/var/cache/microdnf --setopt=reposdir=/etc/yum.repos.d --setopt=varsdir=/etc/dnf --installroot=$installRoot "$@"
