#!/bin/bash

# This script is used to execute the specified command with the given arguments
# Usage: java-exec <command> <args>

if [ $# -eq 0 ]; then
    echo "Usage: $0 <command>"
    exit 1
fi

"$@"
